# https://github.com/chriskempson/base16-xresources/blob/master/base16-brewer.dark.256.xresources
# Base16 Brewer
# Scheme: Timothée Poisot (http://github.com/tpoisot)
# foreground=#ffffff
# background=#1a1b26
# cursor=#ffffff

# color0=#1a1b26
# color1=#e0af68
# color2=#e0af68
# color3=#f0c674
# color4=#ffffff
# color5=#eeeeee
# color6=#ffffff
# color7=#cdd7e0
# color8=#414868
# color9=#e0af68
# color10=#f0c674
# color11=#ffff77
# color12=#ffffff
# color13=#ffffff
# color14=#ffffff
# color15=#ffffff


# bark colorscheme, by (hehe stolen, thanks lung :p) https://github.com/if-not-nil
background=#101010
foreground=#d0d0d0
selection_background #2b2b2b
selection_foreground #101010
url_color #b0b0b0
cursor=#d0d0d0
active_border_color #505050
inactive_border_color #202020
active_tab_background #101010
active_tab_foreground #d0d0d0
inactive_tab_background #202020
inactive_tab_foreground #b0b0b0
tab_bar_background #202020

# normal
color0=#101010
color1=#ab4642
color2=#a1b56c
color3=#f7ca88
color4=#7cafc2
color5=#ba8baf
color6=#86c1b9
color7=#d0d0d0

# bright
color8=#505050
color9=#ab4642
color10=#a1b56c
color11=#f7ca88
color12=#7cafc2
color13=#ba8baf
color14=#86c1b9
color15=#e0e0e0