github.com:
    users:
        1rwxr1xr1x:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: 1rwxr1xr1x
